create table if not exists public.solicitudes_trabajo (id bigint generated by default as identity primary key,nombre text not null,telefono text not null,correo text not null,ciudad text not null,area_interes text not null,perfil text,linkedin text,hoja_vida_ref text,estado text not null default 'Nueva',creado_at timestamptz not null default now());
alter table public.solicitudes_trabajo enable row level security;
drop policy if exists "Candidatos pueden enviar solicitud" on public.solicitudes_trabajo;
create policy "Candidatos pueden enviar solicitud" on public.solicitudes_trabajo for insert to anon with check (true);
drop policy if exists "Personal interno puede consultar candidatos" on public.solicitudes_trabajo;
create policy "Personal interno puede consultar candidatos" on public.solicitudes_trabajo for select to authenticated using (true);
drop policy if exists "Personal interno puede actualizar candidatos" on public.solicitudes_trabajo;
create policy "Personal interno puede actualizar candidatos" on public.solicitudes_trabajo for update to authenticated using (true) with check (true);

-- El bucket debe existir como PRIVADO con el nombre exacto: hojas-vida
drop policy if exists "Candidatos pueden subir hojas de vida" on storage.objects;
create policy "Candidatos pueden subir hojas de vida" on storage.objects for insert to anon with check (bucket_id='hojas-vida');
drop policy if exists "Personal interno puede consultar hojas de vida" on storage.objects;
create policy "Personal interno puede consultar hojas de vida" on storage.objects for select to authenticated using (bucket_id='hojas-vida');
